### PR TITLE
Features improve escape recovery

### PR DESCRIPTION
**Pull request by howardcochran**
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
___
*[pose_follower/src/pose_follower.cpp, line 228 at r1](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2#-LNl_wf2AUQi5z648sbh:-LNl_wf2AUQi5z648sbi:b17nw73) ([raw file](https://github.com/badgertechnologies/navigation_experimental/blob/55eaeb8834f640799f4f3a96128cdb59a843c9dd/pose_follower/src/pose_follower.cpp#L228)):*
> ```cpp
>     // (i.e. a rotation in place), skip the current waypoint to the final
>     // such step, which allows for much smoother rotational motion.
>     while((current_waypoint_ < global_plan_.size() - 2)
> ```

Is it *guaranteed* that global_plan.size() > 1? If not, this loop could go on for a very long time in that case...

**Review by c-andy-martin — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2)* status: all files reviewed, 1 unresolved discussion (waiting on @howardcochran)

**Review by howardcochran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[pose_follower/src/pose_follower.cpp, line 228 at r1](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2#-LNl_wf2AUQi5z648sbh:-LNlj43cEnWq4AEjRtMl:b-d57mr2) ([raw file](https://github.com/badgertechnologies/navigation_experimental/blob/55eaeb8834f640799f4f3a96128cdb59a843c9dd/pose_follower/src/pose_follower.cpp#L228)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Is it *guaranteed* that global_plan.size() > 1? If not, this loop could go on for a very long time in that case...
</blockquote></details>

GOOD CATCH!!!  I pushed a new version of the branch that rewrites this commit to fix the problem.

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation_experimental/2#-:-LNmSixw8U_8RVUv1UQW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
